### ISSUE TITLE
In stage 1, 'pred_target' is not defined

### ISSUE THREAD

**Issue by SouthFlame** [MyeongJin-Kim/Learning-Texture-Invariant-Representation#1]
Hi,
First, thank for your work :)

I have the error message below.

`  
File "train_gta2cityscapes.py", line 408, in <module>
    main()
  File "train_gta2cityscapes.py", line 353, in main
    D_output_target = model_D(F.softmax(pred_target))
UnboundLocalError: local variable 'pred_target' referenced before assignment
`

After I read the code of this line, I think the definition of "pred_target" is missed.

Best regards.

Namyup Kim

**Comment by MyeongJin-Kim** [comment]
I updated the code!

**Comment by SouthFlame** [comment]
Oh, I appreciate your fast response. 
Thanks a lot ;)
