### ISSUE TITLE
Could you upload the CycleGAN Network and Style-swap Network that you trained?

### ISSUE THREAD

**Issue by yanjj16** [MyeongJin-Kim/Learning-Texture-Invariant-Representation#3]
Could you upload the CycleGAN Network and Style-swap Network that you trained ?
It will be very kind of you,if you could provide some more detail information ,such as the Style-swap's training configuration and so on.

**Comment by MyeongJin-Kim** [comment]
Hi, I used default hyperparameters of CycleGAN and Style-swap.

**Comment by yanjj16** [comment]
Could you upload the CycleGAN Network and Style-swap Network that you used ? 
It will take a lot of time to train them from scratch.Thank you !

**Comment by MyeongJin-Kim** [comment]
You can get images generated by CycleGAN from https://github.com/liyunsheng13/BDL
and Style-swap network from https://github.com/rtqichen/style-swap
