### ISSUE TITLE
Could you share the code for SYNTHIA to Cityscapes?

### ISSUE THREAD

**Issue by chentao2016** [MyeongJin-Kim/Learning-Texture-Invariant-Representation#4]
I'm interested in your implementation of the additional technique (class-ratio prior) that reducing the layout gap for SYNTHIA to Cityscapes. Could you share the code for SYNTHIA to Cityscapes?

**Comment by MyeongJin-Kim** [comment]
Hi thanks for your interest. I think there seems to be a misunderstanding.
I didn't use class-ratio prior, but cite [1] which used class-ratio prior.

[1][2019 CVPR] ADVENT- Adversarial Entropy Minimization for Domain Adaptation in Semantic Segmentation
